spring:
  datasource:
    url: jdbc:mysql://localhost:3306/no_problem?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: npdbo
    password: 123
aliyun:
  oss:
    displayUrl:
    accessKey:
    secret:
    endPoint: